version: "3"

services:
  whisper:
    build:
      context: ./infra/whisper
    volumes:
      - ./artifacts:/app/artifacts
      - whisper-data:/root/.cache/whisper

volumes:
  ollama-data:
  whisper-data:
