version: "3"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  whisper:
    build:
      context: ./infra/whisper
    volumes:
      - ./artifacts:/app/artifacts
      - whisper-data:/root/.cache/whisper

volumes:
  ollama-data:
  whisper-data:
